name: expense_tracker_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path: ^1.9.0
  



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  flutter_test:
    sdk: flutter
    


  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

uses-material-design: true


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/app_icon.png
  android: true
  ios: false

